name: Chocolatine

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-REN-2-1-chocolatine-elie.stroun.git"
  EXECUTABLES: "pain_au_chocolat_de_test"

on:
  push:
    branches:
      - '*'
      - '!ga-ignore-*'
  pull_request:
    branches:
      - '*'

jobs:
  check_coding_style_w_epitech_docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - name: Display coding style errors
        run: |
          check.sh $(pwd) $(pwd)
          echo "test"
          exit_code=0;
          cat coding-style-reports.log | while read line; do
            part1=$(echo $line | cut -d: -f1)
            part2=$(echo $line | cut -d: -f2)
            part3=$(echo $line | cut -d: -f3)
            title=$(echo "coding style error")
            error=$(echo $line | cut -d: -f4)
            echo "test"
            exit_code=1
            echo "::error file=$part1, line=$part2, title=$title::$error";
          done < coding-style-reports.log
          echo "plplpl"
          if [ $exit_code -eq 1 ]
          then
            echo "toto"
            exit 1
          fi

  check_program_compilation_w_make:
    needs: check_coding_style_w_epitech_docker
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - name: Build program
        run: make
        timeout-minutes: 2
      - name: Clean build
        run: make clean
      - name: Verify executables
        run: |
          for executable in ${EXECUTABLES//,/ }
          do
            if [ ! -f "$executable" ] || [ ! -x "$executable" ]; then
              echo "$executable is not there or not executable"
              exit 1
            fi
          done

  run_tests:
    needs: check_program_compilation_w_make
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    needs: run_tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}